name: Odin Dutton
description: Odin Dutton's blog
url: http://odindutton.com
permalink: /:title/

markdown: redcarpet

include: [.well-known]

# GitHub Pages defaults:
lsi: false
pygments: true

gems:
  - jekyll-sitemap
