name: Odin Dutton
description: "Odin Dutton's blog"
url: http://odindutton.com
permalink: /:title/

include: [.well-known]

# GitHub Pages defaults:
lsi: false
highlighter: rogue

# jekyll-github-metadata
repository: twe4ked/odindutton.com

gems:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-redirect-from
