title: Odin Dutton
description: "Odin Dutton's blog"
url: http://odindutton.com
permalink: /:title/

include: [.well-known]

# GitHub Pages defaults:
lsi: false
highlighter: rouge
markdown: kramdown

kramdown:
  parse_block_html: true

# jekyll-github-metadata
repository: twe4ked/odindutton.com

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-redirect-from
